spring:
  datasource:
    url: jdbc:mysql:///1610a?serverTimezone=UTC
    username: root
    password: root

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing

  mvc:
    view:
      prefix: /
      suffix: .jsp
  mybatis:
    mapperLocations: classpath:mapping/*.xml


